FROM golang:1.25-alpine AS builder

RUN apk add --no-cache libpcap-dev gcc musl-dev

WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download

COPY cmd/ ./cmd/
COPY internal/ ./internal/
COPY pkg/ ./pkg/
RUN go build -o etr ./cmd/etr

FROM alpine:latest
RUN apk add --no-cache libpcap iproute2 tcpdump

COPY --from=builder /build/etr /usr/local/bin/etr

CMD ["tail", "-f", "/dev/null"]
